### ISSUE TITLE
Docker fails to build as root - missing libx264

### ISSUE THREAD

**Issue by spydmobile** [razuna/razuna_docker_1#3]
fails with:
`**********************************************************************

 Done. The new package has been installed and saved to

 /tmp/lame-3.98.4/lame-ffmpeg_3.98.4-1_amd64.deb

 You can remove it from your system anytime using:

      dpkg -r lame-ffmpeg

**********************************************************************

Cloning into '/tmp/ffmpeg'...
Switched to a new branch 'release/3.0'
Branch release/3.0 set up to track remote branch release/3.0 from origin.
ERROR: libx264 not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
The command '/bin/sh -c /tmp/install-ffmpeg' returned a non-zero code: 1
An error occured during the creating of the image. Error:  The command '/bin/sh -c /tmp/install-ffmpeg' returned a non-zero code: 1
`

**Comment by spydmobile** [comment]
further, I removed docker (Installed with yum install docker) and instead installed and setup docker-ce and docker-composer and tried again - after which the build still failed with the same error.

**Comment by thenitai** [comment]
This has nothing to do with Docker, but with ffmpeg. The docker script has been created some time ago, so it is out-of-date.

This should more be viewed as a guideline. Feel free to change it.
